// AUTH
export const AUTH_START = "[auth] AUTH_START";
export const AUTH_SUCCESS = "[auth] AUTH_SUCCESS";
export const AUTH_FAILURE = "[auth] AUTH_FAILURE";
export const LOG_OUT = "[auth] LOG_OUT_SUCCESS";

// COURSES
export const FETCH_COURSES_START = "[course] FETCH_COURSES_START";
export const FETCH_COURSES_SUCCESS = "[course] FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "[course] FETCH_COURSES_FAILURE";

export const SEARCH_COURSE_START = "[course] SEARCH_COURSE_START";
export const SEARCH_COURSE_SUCCESS = "[course] SEARCH_COURSE_SUCCESS";
export const SEARCH_COURSE_FAILURE = "[course] SEARCH_COURSE_FAILURE";

export const FETCH_CATEGORY_START = "[course] FETCH_CATEGORY_START";
export const FETCH_CATEGORY_SUCCESS = "[course] FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "[course] FETCH_CATEGORY_FAILURE";

export const FETCH_COURSE_CATEGORY_START =
  "[course]  FETCH_COURSE_CATEGORY_START";
export const FETCH_COURSE_CATEGORY_SUCCESS =
  "[course] FETCH_COURSE_CATEGORY_SUCCESS ";
export const FETCH_COURSE_CATEGORY_FAILURE =
  "[course] FETCH_COURSE_CATEGORY_FAILURE";

export const FETCH_CATEGORY_CODE = "[course] FETCH_CATEGORY_CODE";

export const FETCH_COURSE_DETAILS_START = "[course] FETCH_COURSE_DETAILS_START";
export const FETCH_COURSE_DETAILS_SUCCESS =
  "[course] FETCH_COURSE_DETAILS_SUCCESS";
export const FETCH_COURSE_DETAILS_FAILURE =
  "[course] FETCH_COURSE_DETAILS_FAILURE";

export const COURSE_ENROLLED_SUCCESS = "[course] COURSE_ENROLLED_SUCCESS";
export const COURSE_ENROLL_FAILURE = "[course] COURSE_ENROLL_FAILURE";

export const CANCEL_COURSE_ENROLL_SUCCESS =
  "[course] CANCEL_COURSE_ENROLL_SUCCESS";
export const CANCEL_COURSE_ENROLL_FAILURE =
  "[course]  CANCEL_COURSE_ENROLL__FAILURE";

export const FETCH_INFO_ACCOUNT_USER_SUCCESS =
  "[course] FETCH_INFO_ACCOUNT_USER_SUCCESS";
export const FETCH_INFO_ACCOUNT_USER_FAILURE =
  "[course] FETCH_INFO_ACCOUNT_USER_FAILURE";

export const FETCH_COURSES_LIST_START =
  "[course_manage] FETCH_COURSES_LIST_START";
export const FETCH_COURSES_LIST_SUCCESS =
  "[course_manage] FETCH_COURSES_LIST_SUCCESS";
export const FETCH_COURSES_LIST_FAILURE =
  "[course_manage] FETCH_COURSES_LIST_FAILURE";

export const DELETE_COURSE_SUCCESS = "[course_manage] DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "[course_manage] DELETE_COURSE_FAILURE";

export const COURSE_INFO = "[course_manage] COURSE_INFO";

export const FETCH_INFO_USER_COURSES_SUCCESS =
  "[course] FETCH_INFO_USER_COURSES_SUCCESS";
export const FETCH_INFO_USER_COURSES_FAILURE =
  "[course] FETCH_INFO_USER_COURSES_FAILURE";

export const UPDATE_COURSE = "[course-manage] UPDATE_COURSE";

// USERS
export const FETCH_USER_LIST_START = "[user_manage] FETCH_USER_LIST_START";
export const FETCH_USER_LIST_SUCCESS = "[user_manage] FETCH_USER_LIST_SUCCESS";
export const FETCH_USER_LIST_FAILURE = "[user_manage] FETCH_USER_LIST_FAILURE";

export const SEARCH_USER_LIST_START = "[user_manage] SEARCH_USER_LIST_START";
export const SEARCH_USER_LIST_SUCCESS =
  "[user_manage] SEARCH_USER_LIST_SUCCESS";
export const SEARCH_USER_LIST_FAILURE =
  "[user_manage] SEARCH_USER_LIST_FAILURE";

export const FETCH_LIST_USER_TYPE = "[user_manage] FETCH_LIST_USER_TYPE";

export const FETCH_AVAILABLE_COURSE_LIST_SUCCESS =
  "[user_manage] FETCH_AVAILABLE_COURSE_LIST_SUCCESS";
export const FETCH_AVAILABLE_COURSE_LIST_FAILURE =
  "[user_manage] FETCH_AVAILABLE_COURSE_LIST_FAILURE";

export const COURSE_ENROLLMENT_SUCCESS =
  "[user_manage] COURSE_ENROLLMENT_SUCCESS";
export const COURSE_ENROLLMENT_FAILURE =
  "[user_manage] COURSE_ENROLLMENT_FAILURE";

export const FETCH_LIST_COURSE_APPROVAL_SUCCESS =
  "[user_manage] FETCH_LIST_COURSE_APPROVAL_SUCCESS";
export const FETCH_LIST_COURSE_APPROVAL_FAILURE =
  "[user_manage] FETCH_LIST_COURSE_APPROVAL_FAILURE";

export const FETCH_LIST_COURSE_APPROVED_SUCCESS =
  "[user_manage] FETCH_LIST_COURSE_APPROVED_SUCCESS";
export const FETCH_LIST_COURSE_APPROVED_FAILURE =
  "[user_manage] FETCH_LIST_COURSE_APPROVED_FAILURE";

export const DELETE_USER_SUCCESS = "[user_manage] DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "[user_manage] DELETE_USER_FAILURE";

export const USER_INFO = "[user_manage] USER_INFO";

export const UPDATE_USER_INFO = "[user_manage] UPDATE_USER_INFO";

export const ADD_USER = "[user_manage] ADD_USER";

export const CHOOSE_COURSE_TYPE = "[filter] CHOOSE_COURSE_TYPE";
export const CHOOSE_GROUP = "[filter] CHOOSE_GROUP";
